import type {
  BudgetExpense,
  BudgetTransfer,
  DiaryEntry,
  Note,
  ScheduleItem,
  TodoItem,
  User,
} from '../api/types';
import type { DemoTrip } from './demoData';

const baseUrl =
  typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL ? import.meta.env.BASE_URL : '/';
const screenshotTripBanner = `${baseUrl}demo/lissabon.jpg`;

/**
 * Feste Systemzeit für die Baseline-Screenshots (1 Woche vor Abreise).
 * Freitag, 07. August 2026, 10:00:00 UTC.
 */
export const SCREENSHOT_REFERENCE_DATE = '2026-08-07T10:00:00.000Z';

/**
 * Fester Urlaubszeitraum für Mitte August 2026 (10 Tage).
 * Freitag, 14. August 2026 bis Sonntag, 23. August 2026.
 */
export const SCREENSHOT_TRIP_DATES = {
  start: '2026-08-14',
  end: '2026-08-23',
} as const;

export const SCREENSHOT_USER: User = {
  id: 1,
  username: 'Mia',
  avatar: '🦊',
  email: 'mia@example.com',
  is_admin: true,
  must_change_password: false,
};

export const SCREENSHOT_PARTNER: User = {
  id: 2,
  username: 'Amari',
  avatar: '🐼',
  email: 'jo@example.com',
  is_admin: false,
  must_change_password: false,
};

export const SCREENSHOT_TRIP: DemoTrip = {
  id: 1,
  name: 'Sommerurlaub Lissabon',
  destination: 'Lissabon, Portugal',
  start_date: SCREENSHOT_TRIP_DATES.start,
  end_date: SCREENSHOT_TRIP_DATES.end,
  maps_link: 'https://maps.google.com/?q=Lissabon',
  lat: 38.7223,
  lng: -9.1393,
  image_url: screenshotTripBanner,
  packing_category_required: 0,
  weather_model: 'ecmwf_ifs025',
};

export const SCREENSHOT_EXTRA_TRIPS: DemoTrip[] = [
  {
    id: 2,
    name: 'Alpenüberquerung E5',
    destination: 'Oberstdorf – Meran',
    start_date: '2026-09-05',
    end_date: '2026-09-13',
    maps_link: '',
    lat: 47.408,
    lng: 10.279,
    image_url: '',
    packing_category_required: 1,
    weather_model: 'ecmwf_ifs025',
  },
  {
    id: 3,
    name: 'Wochenende in Amsterdam',
    destination: 'Amsterdam, Niederlande',
    start_date: '2026-10-02',
    end_date: '2026-10-04',
    maps_link: '',
    lat: 52.3676,
    lng: 4.9041,
    image_url: '',
    packing_category_required: 0,
    weather_model: 'ecmwf_ifs025',
  },
];

export const SCREENSHOT_TODOS: TodoItem[] = [
  {
    id: 1,
    trip_id: 1,
    title: 'Reisepässe auf Gültigkeit prüfen',
    assigned_to_user_id: 1,
    due_date: '2026-08-07',
    period: 'before',
    priority: 'high',
    note: 'Muss mind. 6 Monate über das Rückreisedatum hinaus gültig sein',
    done: 1,
  },
  {
    id: 2,
    trip_id: 1,
    title: 'Auslandskrankenversicherung abschließen',
    assigned_to_user_id: 2,
    due_date: '2026-08-10',
    period: 'before',
    priority: 'medium',
    note: 'Versicherungsschein als PDF unter Dokumente hinterlegen',
    done: 1,
  },
  {
    id: 3,
    trip_id: 1,
    title: 'Pflanzen gießen & Nachbarn Schlüssel geben',
    assigned_to_user_id: 2,
    due_date: '2026-08-14',
    period: 'before',
    priority: 'high',
    note: 'Blumen auf dem Balkon gießen und Briefkasten leeren',
    done: 0,
  },
  {
    id: 4,
    trip_id: 1,
    title: 'Online-Check-in für Hinflug durchführen',
    assigned_to_user_id: 1,
    due_date: '2026-08-14',
    period: 'before',
    priority: 'high',
    note: 'Öffnet 24 Stunden vor Abflug auf der Airline-Website',
    done: 0,
  },
  {
    id: 5,
    trip_id: 1,
    title: 'Viva-Viagem-Karten an Metrostation aufladen',
    assigned_to_user_id: null,
    due_date: '2026-08-15',
    period: 'during',
    priority: 'medium',
    note: 'Am Fahrkartenautomaten am Flughafen oder Rossio-Bahnhof',
    done: 0,
  },
  {
    id: 6,
    trip_id: 1,
    title: 'Tickets für Mosteiro dos Jerónimos vorab buchen',
    assigned_to_user_id: 1,
    due_date: '2026-08-16',
    period: 'during',
    priority: 'high',
    note: 'Zeitfenster-Tickets sichern, um langes Anstehen zu vermeiden',
    done: 0,
  },
  {
    id: 7,
    trip_id: 1,
    title: 'Pastéis de Belém frisch für die Familie besorgen',
    assigned_to_user_id: 2,
    due_date: '2026-08-22',
    period: 'during',
    priority: 'low',
    note: 'Am Abreisetag frisch in der Antiga Confeitaria de Belém holen',
    done: 0,
  },
];

export const SCREENSHOT_SCHEDULE: ScheduleItem[] = [
  {
    id: 1,
    trip_id: 1,
    date: '2026-08-14',
    end_date: null,
    time: '07:00',
    end_time: '10:30',
    title: 'Hinflug nach Lissabon',
    note: 'Flug TP543 ab Frankfurt, Ankunft Terminal 1',
    location: 'Flughafen Lissabon (LIS)',
    maps_link: null,
    lat: 38.7742,
    lng: -9.1342,
    category: 'travel',
    spot_id: null,
    idea_id: null,
  },
  {
    id: 2,
    trip_id: 1,
    date: '2026-08-14',
    end_date: null,
    time: '15:00',
    end_time: null,
    title: 'Check-in Hotel Alfama',
    note: 'Klimaanlage vorhanden, Schlüsselbox Code #4821',
    location: 'Rua de São Pedro 12, Alfama',
    maps_link: null,
    lat: 38.72,
    lng: -9.12,
    category: 'excursion',
    spot_id: 1,
    idea_id: null,
  },
  {
    id: 3,
    trip_id: 1,
    date: '2026-08-15',
    end_date: null,
    time: '09:30',
    end_time: '16:00',
    title: 'Panoramatour Alfama & Belém',
    note: 'Start beim Hotel Alfama',
    location: 'Lissabon',
    maps_link: null,
    lat: null,
    lng: null,
    category: 'excursion',
    spot_id: null,
    idea_id: 3,
  },
  {
    id: 4,
    trip_id: 1,
    date: '2026-08-15',
    end_date: null,
    time: '19:00',
    end_time: null,
    title: 'Abendessen im Time Out Market',
    note: 'Gute Auswahl für beide Geschmäcker',
    location: 'Mercado da Ribeira',
    maps_link: null,
    lat: 38.7069,
    lng: -9.1459,
    category: 'other',
    spot_id: 3,
    idea_id: null,
  },
  {
    id: 5,
    trip_id: 1,
    date: '2026-08-16',
    end_date: null,
    time: '09:00',
    end_time: '11:00',
    title: 'Torre de Belém besichtigen',
    note: 'Unbedingt früh morgens, wird schnell voll',
    location: 'Belém',
    maps_link: null,
    lat: 38.6916,
    lng: -9.2159,
    category: 'excursion',
    spot_id: 2,
    idea_id: null,
  },
  {
    id: 6,
    trip_id: 1,
    date: '2026-08-19',
    end_date: null,
    time: '09:00',
    end_time: '17:00',
    title: 'Tagestour Sintra',
    note: 'Mit dem Zug ab Rossio, ca. 40 Minuten',
    location: 'Sintra & Palácio da Pena',
    maps_link: null,
    lat: 38.7884,
    lng: -9.3908,
    category: 'excursion',
    spot_id: null,
    idea_id: 1,
  },
  {
    id: 7,
    trip_id: 1,
    date: '2026-08-23',
    end_date: null,
    time: '18:00',
    end_time: '21:30',
    title: 'Rückflug nach Frankfurt',
    note: 'Flug TP544 nach Frankfurt',
    location: 'Flughafen Lissabon (LIS)',
    maps_link: null,
    lat: 38.7742,
    lng: -9.1342,
    category: 'travel',
    spot_id: null,
    idea_id: null,
  },
];

export const SCREENSHOT_BUDGET_EXPENSES: BudgetExpense[] = [
  {
    id: 1,
    trip_id: 1,
    title: 'Reiseführer & Straßenkarte Lissabon',
    category: 'Souvenirs',
    amount: 24.9,
    paid_by_user_id: 1,
    date: '2026-08-04',
    note: 'Vorab im Buchhandel besorgt',
    budget_id: 1,
  },
  {
    id: 2,
    trip_id: 1,
    title: 'Metro-Karten vorab aufgeladen',
    category: 'Transport',
    amount: 40.0,
    paid_by_user_id: 2,
    date: '2026-08-12',
    note: '2x Viva Viagem mit Zapping-Guthaben',
    budget_id: 1,
  },
  {
    id: 3,
    trip_id: 1,
    title: 'Flughafentransfer Metro',
    category: 'Transport',
    amount: 28.5,
    paid_by_user_id: 1,
    date: '2026-08-14',
    note: 'Metro-Tickets & Snack am Flughafen',
    budget_id: 1,
  },
  {
    id: 4,
    trip_id: 1,
    title: 'Time Out Market Abendessen',
    category: 'Essen & Trinken',
    amount: 64.0,
    paid_by_user_id: 2,
    date: '2026-08-15',
    note: 'Petiscos & Craft Beer',
    budget_id: 1,
  },
  {
    id: 5,
    trip_id: 1,
    title: 'Torre de Belém & Mosteiro Eintritt',
    category: 'Aktivitäten & Spaß',
    amount: 32.0,
    paid_by_user_id: 1,
    date: '2026-08-16',
    note: 'Kombi-Tickets online gekauft',
    budget_id: 1,
  },
  {
    id: 6,
    trip_id: 1,
    title: 'Sintra Zug & Pena-Palast Tickets',
    category: 'Aktivitäten & Spaß',
    amount: 78.0,
    paid_by_user_id: 2,
    date: '2026-08-19',
    note: 'Zug ab Rossio + Palácio da Pena Eintritt',
    budget_id: 1,
  },
  {
    id: 7,
    trip_id: 1,
    title: 'Hotel Alfama Endabrechnung',
    category: 'Unterkunft',
    amount: 560.0,
    paid_by_user_id: 1,
    date: '2026-08-23',
    note: '9 Nächte inkl. Kurtaxe vor Ort',
    budget_id: 1,
  },
];

export const SCREENSHOT_BUDGET_TRANSFERS: BudgetTransfer[] = [
  {
    id: 1,
    trip_id: 1,
    from_user_id: 2,
    to_user_id: 1,
    amount: 120.0,
    date: '2026-08-17',
    note: 'Teilausgleich für Hotel',
  },
];

export const SCREENSHOT_DIARY: DiaryEntry[] = [
  {
    id: 1,
    trip_id: 1,
    author_id: 1,
    title: 'Ankunft in Lissabon',
    content:
      'Der Flug war pünktlich und der Anflug über den Tejo spektakulär! Das Hotel Alfama liegt mitten in den verwinkelten Gassen. Zum Abendessen gab es frischen Fisch und Vino Verde.',
    content_format: 'plain',
    images: [],
    date: '2026-08-14',
    created_at: '2026-08-14T20:30:00Z',
    updated_at: null,
    excursion_ids: [],
    spot_ids: [1],
    editor_ids: [],
    is_draft: 0,
  },
  {
    id: 2,
    trip_id: 1,
    author_id: 2,
    title: 'Erkundungstour durch die Alfama & Belém',
    content:
      'Traumhaftes Sommerwetter bei 28 Grad. Wir sind mit der historischen Straßenbahn 28 gefahren und haben am Miradouro de Santa Luzia die Aussicht genossen. Abends leckere Petiscos im Time Out Market!',
    content_format: 'plain',
    images: [],
    date: '2026-08-15',
    created_at: '2026-08-15T21:00:00Z',
    updated_at: null,
    excursion_ids: [3],
    spot_ids: [2, 3, 8],
    editor_ids: [],
    is_draft: 0,
  },
];

/**
 * Realistisches Lissabon-Sommerwetter für 18 Tage (06.08.2026 bis 23.08.2026),
 * das den Abreisetag, alle 10 Urlaubstage sowie die Tage davor abdeckt.
 */
export const SCREENSHOT_WEATHER = {
  daily: {
    time: [
      '2026-08-06',
      '2026-08-07',
      '2026-08-08',
      '2026-08-09',
      '2026-08-10',
      '2026-08-11',
      '2026-08-12',
      '2026-08-13',
      '2026-08-14',
      '2026-08-15',
      '2026-08-16',
      '2026-08-17',
      '2026-08-18',
      '2026-08-19',
      '2026-08-20',
      '2026-08-21',
      '2026-08-22',
      '2026-08-23',
    ],
    weathercode: [0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0],
    temperature_2m_max: [27, 28, 26, 29, 25, 27, 28, 30, 28, 27, 29, 26, 27, 28, 30, 29, 27, 28],
    temperature_2m_min: [18, 19, 18, 19, 17, 18, 19, 20, 19, 18, 19, 18, 18, 19, 20, 19, 18, 18],
    precipitation_probability_max: [5, 5, 10, 0, 20, 10, 5, 0, 5, 5, 10, 15, 10, 5, 0, 0, 10, 5],
  },
};

export const SCREENSHOT_NOTES: Note[] = [
  {
    id: 1,
    trip_id: 1,
    title: 'WLAN & Notfallkontakte',
    content: 'Hotel-WLAN: siehe Zimmerkarte. Notfallnummer Portugal: 112.',
    content_format: 'plain',
    created_by: 1,
    created_at: '2026-08-05T11:35:00.000Z',
    updated_at: null,
    is_draft: 0,
  },
];
